languageCode = "fr"
languageName = "Français"
weight = 1
title = "Blog - Antoine Sesini"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Un peu d'infrastructure, de réseau et de dev."

[params.author]
  name = "Antoine Sesini"
  image = "img/avatar.jpeg"
  headline = "✨ Un peu d'infrastructure, de réseau et de dev. ✨"
  bio = "✨ Un peu d'infrastructure, de réseau et de dev. ✨"
  links = [
    { linkedin = "https://linkedin.com/in/antoine-sesini-a77b98202" },
    { github = "https://github.com/antoinesesini" },
  ]